name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.24.3
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -coverprofile=coverage.txt -v ./...

      - name: Upload Coverage
        if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) || github.event_name == 'push'
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
  build-container-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout Source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

    - name: Build Multi-Platform Container Image (verification only)
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
        -t build-container-test:latest .

    - name: Build and Load Native Platform Image for Testing
      run: |
        docker buildx build --platform linux/amd64 --load \
        -t build-container-test:latest .

