name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.24.3
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -coverprofile=coverage.txt -v ./...

      - name: Upload Coverage
        if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) || github.event_name == 'push'
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  goreleaser-test:
    name: GoReleaser Cross-Compile Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
      OSX_CROSS_TOOLCHAIN_REPOSITORY: https://github.com/abhisek/osxcross
      OSX_CROSS_MACOS_SDK_VERSION: "12.3"
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2
      - uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # v2
      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: 1.24.3
          check-latest: true
      - name: Install OSX Cross Compiler Build Tools
        run: sudo apt-get install -y -qq build-essential clang gcc g++ gcc-mingw-w64 zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev cmake libxml2-dev libssl-dev xz-utils
      - name: Setup OSX Cross Compiler Tool Chain Environment
        run: |
          echo "OSXCROSS_DIR=$(dirname $GITHUB_WORKSPACE)/osxcross" >> $GITHUB_ENV
      - name: Clone OSX Cross Compiler Tool Chain
        run: git clone $OSX_CROSS_TOOLCHAIN_REPOSITORY $OSXCROSS_DIR
      - name: Setup Cache for OSX Cross Compiler Tool Chain
        id: osxcross-cache
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3
        with:
          key: ${{ runner.os }}-osxcross-${{ env.OSX_CROSS_MACOS_SDK_VERSION }}
          path: |
            ${{ env.OSXCROSS_DIR }}/target/bin
      - name: Build OSX Cross Compiler Tool Chain
        if: steps.osxcross-cache.outputs.cache-hit != 'true'
        run: |
          cd $OSXCROSS_DIR
          SDK_VERSION=$OSX_CROSS_MACOS_SDK_VERSION UNATTENDED=yes ./build.sh
      - name: Add OSX Cross Compiler Tool Chain to Path
        run: |
          echo "$OSXCROSS_DIR/target/bin" >> $GITHUB_PATH
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --clean --snapshot
